_target_: models.unet.UNet
in_channels: 4
out_channels: 1
channels: [48, 64, 128, 256]
strides: [2, 2, 2]
num_res_blocks: 2
dropout: 0.0
context_embedding_dim: 128
attention_levels: [False, False, True]
use_context: False
