defaults:
  - dataset: tomogram
  - characteristics: full
  - model: unet_att
  - generation: sgdm
  - optimizer: adamw
  - scheduler: cosine_with_warmup
  - trainer: default
  - logger: wandb
  - _self_

seed: 43
batch_size: 8
log_epochs: [49, 1000, 25]
model_name: tomogram_generator
checkpoint_dir: /kaggle/working/checkpoints

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
